name = "dotenv_gleam"
version = "1.0.3"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "dotenv for Gleam"
licences = ["MIT"]
links = [
  {title = "gleam", href = "https://gleam.run"}
]
repository = { type = "github", user = "Grubba27", repo = "dotenv_gleam" }


[dependencies]
gleam_stdlib = "~> 0.31"
gleam_erlang = "~> 0.22"

[dev-dependencies]
gleeunit = "~> 0.10"
